default: &default
  adapter: postgresql
  host: <%= Rails.application.secrets[:db_host] %>
  port: <%= Rails.application.secrets[:db_port] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  database: <%= Rails.application.secrets[:db_name] %>
  username: <%= Rails.application.secrets[:db_username] %>
  password: <%= Rails.application.secrets[:db_password] %>
development:
  <<: *default
test:
  <<: *default
  database: auto_parts_store_test
production:
  <<: *default
