shared:
  email_from: 'admin@example.com'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_username: <%= ENV["DB_USERNAME"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>
  db_name: <%= ENV["DB_NAME"] %>
  db_host: <%= ENV["DB_HOST"] %>
  db_port: <%= ENV["DB_PORT"] %>
  frontend_host: "https://app.auto_parts_store.com"
  backend_host: "https://api.auto_parts_store.com"
development:
test:
production:
